// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDk7Wgt9NoZ7h7GkS3XEE9ZeIYpEl3ANc',
    appId: '1:611313755835:web:6cdbe09ace0ae3495deb9e',
    messagingSenderId: '611313755835',
    projectId: 'posternova-5c2db',
    authDomain: 'posternova-5c2db.firebaseapp.com',
    storageBucket: 'posternova-5c2db.firebasestorage.app',
    measurementId: 'G-0GM20C29KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5cAS5__zd5SWueBhaqdfdksA0P5gwpU',
    appId: '1:611313755835:android:88a1f78e36f8deff5deb9e',
    messagingSenderId: '611313755835',
    projectId: 'posternova-5c2db',
    storageBucket: 'posternova-5c2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr7Ix-47bY8SnIjV8hoeugoKB1EWX_Uko',
    appId: '1:611313755835:ios:4846f5675755dd6a5deb9e',
    messagingSenderId: '611313755835',
    projectId: 'posternova-5c2db',
    storageBucket: 'posternova-5c2db.firebasestorage.app',
    iosBundleId: 'com.example.posterAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr7Ix-47bY8SnIjV8hoeugoKB1EWX_Uko',
    appId: '1:611313755835:ios:4846f5675755dd6a5deb9e',
    messagingSenderId: '611313755835',
    projectId: 'posternova-5c2db',
    storageBucket: 'posternova-5c2db.firebasestorage.app',
    iosBundleId: 'com.example.posterAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDk7Wgt9NoZ7h7GkS3XEE9ZeIYpEl3ANc',
    appId: '1:611313755835:web:389b784cfc36e96e5deb9e',
    messagingSenderId: '611313755835',
    projectId: 'posternova-5c2db',
    authDomain: 'posternova-5c2db.firebaseapp.com',
    storageBucket: 'posternova-5c2db.firebasestorage.app',
    measurementId: 'G-K7EQTMLXEQ',
  );
}
